export const BUFF_COLORS = {
    heal:'#4f4',
    speed:'#0ff',
    homing:'#ff0',
    invis:'#aaa',
    shrink:'#f8f',
    shield:'#6cf',
    rapidfire:'#fa0',
    bigbullet:'#f55',
    clone:'#88f',
    shotgun:'#f80',
    ricochet:'#0f8',
    giantEnemy:'#f0f',
    reverse:'#08f',
    explosive:'#f44',
    root:'#aa0',
    silence:'#b59bff',
    pierce:'#5fd6ff',
    poison:'#6cff5f',
    nuke:'#ffe76b',
    possession:'#8b00ff',
    trail:'#ff0000',
    fireRate:'#ff6b35',
    fury:'#dc143c',
    lifeSteal:'#ef4444',
    bounceShot:'#f97316',
    bossPierce:'#38bdf8',
    bossFireRate:'#fb7185',
    bossMoveSpeed:'#22c55e',
    twinShot:'#a855f7',
    magnetSmall:'#60a5fa',
    shotSplit:'#facc15',
    shotSplit4:'#fde047',
    ricochetTracking:'#2dd4bf',
    poisonShot:'#bbf7d0',
    microShield:'#7dd3fc',
    criticalHit:'#fb7185',
    bossShield:'#6ee7b7',
    slowMotion10:'#93c5fd',
    fireIceShot:'#f472b6',
    damageBoost:'#f973ab',
    maxHpUp:'#fcd34d',
    bulletDeflect:'#a5b4fc',
    debuffResistance:'#34d399',
    luckUp:'#fde68a',
    miniTank:'#60a5fa',
    doubleShot:'#fb923c'
};

export const buffTypes = [
    'heal','speed','homing','invis','shrink','shield','rapidfire','bigbullet','clone',
    'shotgun','ricochet','giantEnemy','reverse','explosive','root','silence','pierce','poison','nuke',
    'possession','trail','fury'
];

export const bossModeBuffs = [
    'lifeSteal',
    'bounceShot',
    'bossPierce',
    'bossFireRate',
    'bossMoveSpeed',
    'twinShot',
    'magnetSmall',
    'shotSplit',
    'shotSplit4',
    'ricochetTracking',
    'poisonShot',
    'bossShield',
    'microShield',
    'slowMotion10',
    'fireIceShot',
    'criticalHit',
    'damageBoost',
    'maxHpUp',
    'bulletDeflect',
    'debuffResistance',
    'luckUp',
    'miniTank',
    'doubleShot'
];

export const bossBuffRarities = {
    bossFireRate: 'common',
    bossMoveSpeed: 'common',
    bounceShot: 'uncommon',
    bossPierce: 'uncommon',
    magnetSmall: 'uncommon',
    debuffResistance: 'uncommon',
    luckUp: 'uncommon',
    lifeSteal: 'rare',
    slowMotion10: 'rare',
    poisonShot: 'rare',
    damageBoost: 'rare',
    maxHpUp: 'rare',
    twinShot: 'epic',
    shotSplit: 'epic',
    shotSplit4: 'epic',
    ricochetTracking: 'epic',
    bulletDeflect: 'epic',
    doubleShot: 'epic',
    bossShield: 'legendary',
    microShield: 'legendary',
    miniTank: 'legendary',
    fireIceShot: 'mythical',
    criticalHit: 'mythical'
};

export const bossModeBuffWeights = {
    lifeSteal: 6,
    bounceShot: 6,
    bossPierce: 6,
    bossFireRate: 6,
    bossMoveSpeed: 6,
    twinShot: 6,
    magnetSmall: 6,
    shotSplit: 6,
    shotSplit4: 4,
    ricochetTracking: 5,
    poisonShot: 6,
    bossShield: 6,
    microShield: 4,
    slowMotion10: 6,
    fireIceShot: 25,
    criticalHit: 8,
    damageBoost: 8,
    maxHpUp: 8,
    bulletDeflect: 5,
    debuffResistance: 7,
    luckUp: 7,
    miniTank: 3,
    doubleShot: 5
};